---
- name: Getting etcd release
  ansible.builtin.unarchive:
    src: "{{ etcd_download_url }}/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-{{ host_architecture }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Installing etcd to binary dir
  ansible.builtin.copy:
    src: "/tmp/etcd-{{ etcd_version }}-linux-{{ host_architecture }}/{{ item }}"
    dest: "{{ etcd_binary_dir }}/{{ item }}"
    remote_src: yes
    mode: 0511
  with_items:
    - etcd
    - etcdctl

- name: Copying etcd config envs
  ansible.builtin.template:
    src: etcd.env.j2
    dest: /etc/etcd/etcd.env
  notify: Reload etcd

- name: Copying etcdctl config envs
  ansible.builtin.template:
    src: etcdctl.sh.j2
    dest: /etc/profile.d/etcdctl.sh

- name: Copying systemd unit
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify: Reload etcd
